apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-app-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/site-1/demo-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
